/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/../services/AIService`; params?: Router.UnknownInputParams; } | { pathname: `/../components/chat/MessageBalloon`; params?: Router.UnknownInputParams; } | { pathname: `/../components/chat/ProductList`; params?: Router.UnknownInputParams; } | { pathname: `/../components/chat/CartModal`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useAIChat`; params?: Router.UnknownInputParams; } | { pathname: `/../services/UserService`; params?: Router.UnknownInputParams; } | { pathname: `/../services/ProductService`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/services/httpService`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/../services/AIService`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/chat/MessageBalloon`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/chat/ProductList`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/chat/CartModal`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useAIChat`; params?: Router.UnknownOutputParams; } | { pathname: `/../services/UserService`; params?: Router.UnknownOutputParams; } | { pathname: `/../services/ProductService`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/register`; params?: Router.UnknownOutputParams; } | { pathname: `/services/httpService`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/../services/AIService${`?${string}` | `#${string}` | ''}` | `/../components/chat/MessageBalloon${`?${string}` | `#${string}` | ''}` | `/../components/chat/ProductList${`?${string}` | `#${string}` | ''}` | `/../components/chat/CartModal${`?${string}` | `#${string}` | ''}` | `/../hooks/useAIChat${`?${string}` | `#${string}` | ''}` | `/../services/UserService${`?${string}` | `#${string}` | ''}` | `/../services/ProductService${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cart${`?${string}` | `#${string}` | ''}` | `/cart${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chat${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/auth${`?${string}` | `#${string}` | ''}` | `/auth/register${`?${string}` | `#${string}` | ''}` | `/services/httpService${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/../services/AIService`; params?: Router.UnknownInputParams; } | { pathname: `/../components/chat/MessageBalloon`; params?: Router.UnknownInputParams; } | { pathname: `/../components/chat/ProductList`; params?: Router.UnknownInputParams; } | { pathname: `/../components/chat/CartModal`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useAIChat`; params?: Router.UnknownInputParams; } | { pathname: `/../services/UserService`; params?: Router.UnknownInputParams; } | { pathname: `/../services/ProductService`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/services/httpService`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
